New Isolation Migration page
shotgunsoftware/developer.shotgunsoftware.com pull request #165
Opened 2020-09-21 15:58 UTC by david-richer-adsk

2020-09-21 16:09 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/47a8341e116f4d7b3c2240d193cc7eac7922dc7b/index.html)

2020-09-22 15:10 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/be266f802e0eb6e350552ff7f723a208b9201428/index.html)

2020-09-22 15:13 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/3e9972ec3c469487b8280a29b7c29912fd156a4e/index.html)

2020-09-23 18:18 UTC, guillaume-brossard-adsk requested changes

2020-09-23 18:18 UTC, guillaume-brossard-adsk commented on docs/en/trusted-solutions/tier1/setup/migration.md
> +---
Can you add a "Next Step" section in Fine Tuning pointing to Migration?

2020-09-23 18:18 UTC, guillaume-brossard-adsk commented on docs/en/trusted-solutions/tier1/setup/migration.md
> +
Ask the Shotgun team to start the migration process in support ticket/slack

2020-09-23 18:44 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/23db79cbeb74d128c5e239dee63b9028561d7c54/index.html)

2020-09-23 18:46 UTC, david-richer-adsk commented
CR fix done

2020-09-23 18:59 UTC, guillaume-brossard-adsk approved these changes

2020-09-23 19:00 UTC, merged