SG-21012 Add event MD files and replace shotgun instances
shotgunsoftware/developer.shotgunsoftware.com pull request #182
Opened 2021-02-18 21:34 UTC by zamu5

Add 7 files from shotgunEvents tool over to markdown in the developer site

2021-02-19 00:18 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-installation.md
> +{% include info title="Note" content="**Please Note:** If you have installed the daemon on Windows in a network location or if you have configured it to read and write logs and other resources from a
```suggestion
{% include info title="Note" content="If you have installed the daemon on Windows in a network location or if you have configured it to read and write logs and other resources from a network location you will need to edit the service's properties to change the user running the service from the "local machine" account to a domain account that has access to the network resources." %}
```

2021-02-19 00:20 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-api.md
> +{% include info title="Note" content="**Note:** Implementing a callback as a `__call__` method on an object instance is possible but left as an exercise for the user." %}
```suggestion
{% include info title="Note" content="Implementing a callback as a `__call__` method on an object instance is possible but left as an exercise for the user." %}
```

2021-02-19 00:20 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-configuration.md
> +accommodate this." %}
```suggestion
{% include info title="Note" content="The default values used here may require root access (for example, to write to the/var/log directory). The examples provided use are run using `sudo` to accommodate this." %}
```

2021-02-19 00:21 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-configuration.md
> +{% include info title="Note" content="NOTE: there are variables in the logArgs.py file that need to be filled in with appropriate values. '$DEMO_SCRIPT_NAMES$' and '$DEMO_API_KEY$' must be edited to
```suggestion
{% include info title="Note" content="There are variables in the logArgs.py file that need to be filled in with appropriate values. '$DEMO_SCRIPT_NAMES$' and '$DEMO_API_KEY$' must be edited to contain the same values that were used in the shotgunEventDaemon.conf file in order for the logging to function correctly." %}
```

2021-02-19 00:23 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-configuration.md
> +`/usr/local/shotgun/shotgunEvents/plugins` or `C:\shotgun\shotgunEvents\plugins` on Windows)" %}
```suggestion
{% include info title="Note" content="There is no default value here. You must set the value to the location(s) of your plugin files (ie:`/usr/local/shotgun/shotgunEvents/plugins` or `C:\shotgun\shotgunEvents\plugins` on Windows)" %}
```

2021-02-19 00:24 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-configuration.md
> +with a valid value (ie. `noreply@mystudio.com`)." %}
```suggestion
{% include info title="Note" content="There is no default value here. You must replace`support@yourdomain.com` with a valid value (ie. `noreply@mystudio.com`)." %}
```

2021-02-19 00:24 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-configuration.md
> +with a valid value (ie. `shotgun_admin@mystudio.com`)." %}
```suggestion
{% include info title="Note" content="There is no default value here. You must replace `you@yourdomain.com` with a valid value (ie. `shotgun_admin@mystudio.com`)." %}
```

2021-02-19 00:25 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-example-plugins.md
> +{% include info title="Note" content="Note: the plugin won't stop but any failed attempts won't be retried." %}
```suggestion
{% include info title="Note" content="The plugin won't stop but any failed attempts won't be retried." %}
```

2021-02-19 00:26 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-installation.md
> +{% include info title="Note" content="**Windows Note:** You could use `C:\shotgun\shotgunEvents` if you have a Windows server but for this documentation we will be using the Linux path." %}
```suggestion
{% include info title="Note" content="**For Windows:** You could use `C:\shotgun\shotgunEvents` if you have a Windows server but for this documentation we will be using the Linux path." %}
```

2021-02-19 00:27 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-api.md
> +{% include info title="Note" content="**Note:** The point of the `args` argument is for you to be able to process time consuming stuff in the [`registerCallbacks`](#wiki-registerCallbacks) function a
```suggestion
{% include info title="Note" content="The point of the `args` argument is for you to be able to process time consuming stuff in the [`registerCallbacks`](#wiki-registerCallbacks) function and have it passed back to you at event processing time." %}
```

2021-02-19 00:28 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-configuration.md
> +{% include info title="Note" content="**Windows note:** Windows users will need to change all the paths in the configuration file for Windows equivalents. We suggest keeping all paths, including logg
```suggestion
{% include info title="Note" content="**For Windows:** Windows users will need to change all the paths in the configuration file for Windows equivalents. We suggest keeping all paths, including logging, under one single location for the sake of simplicity. This documentation tends to refer to `C:\shotgun\shotgunEvents` when mentioning Windows paths." %}
```

2021-02-19 00:29 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-configuration.md
> +the `shotgunEventDaemon.py` script" %}
```suggestion
{% include info title="Note" content="If for some reason the above won't work for you, the search paths for the config file are located in the `_getConfigPath()` function at the bottom of the `shotgunEventDaemon.py` script" %}
```

2021-02-19 00:29 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-configuration.md
> +{% include info title="Note" content="**Windows Note:** The `/etc` doesn't exist on Windows so the configuration file should be put in the same directory as the Python files." %}
```suggestion
{% include info title="Note" content="**For Windows** The `/etc` doesn't exist on Windows so the configuration file should be put in the same directory as the Python files." %}
```

2021-02-19 00:30 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-configuration.md
> +accommodate this." %}
```suggestion
{% include info title="Note" content="The default values used here may require root access (for example, to write to the/var/log directory). The examples provided use are run using `sudo` to accommodate this." %}
```

2021-02-19 00:30 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-configuration.md
> +machine starts up and is given root privileges at that point." %}
```suggestion
{% include info title="Note" content="The shotgunEventDaemon will have to have write permissions for this directory. In a typical setup, the daemon is set to run automatically when the machine starts up and is given root privileges at that point." %}
```

2021-02-19 00:31 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-configuration.md
> +the URL for your Shotgun server (ie. https://awesome.shotgunstudio.com)" %}
```suggestion
{% include info title="Note" content="There is no default value here. Set the `SG_ED_SITE_URL` environment variable to the URL for your Shotgun server (ie. https://awesome.shotgunstudio.com)" %}
```

2021-02-19 00:31 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-configuration.md
> +to the Script name for your Shotgun server (ie. `shotgunEventDaemon`)" %}
```suggestion
{% include info title="Note" content="There is no default value here. Set the `SG_ED_SCRIPT_NAME` environment variable to the Script name for your Shotgun server (ie. `shotgunEventDaemon`)" %}
```

2021-02-19 00:32 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-configuration.md
> +`0123456789abcdef0123456789abcdef01234567`)" %}
```suggestion
{% include info title="Note" content="There is no default value here. Set the `SG_ED_API_KEY` environment variable to the Application Key for your Script name above (ie:`0123456789abcdef0123456789abcdef01234567`)" %}
```

2021-02-19 00:32 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-configuration.md
> +will not see updates live." %}
```suggestion
{% include info title="Note" content="The Shotgun UI will *only* show updates live for the browser session that spawned the original event. Other browser windows with the same page open will not see updates live." %}
```

2021-02-19 00:33 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-configuration.md
> +token with the address of your SMTP server (ie. `smtp.mystudio.com`)." %}
```suggestion
{% include info title="Note" content="There is no default value here. You must replace the smtp.yourdomain.com token with the address of your SMTP server (ie. `smtp.mystudio.com`)." %}
```

2021-02-19 00:35 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-technical-details.md
> +{% include info title="Note" content="**Note:** Internally the filenames are put in a list and sorted." %}
```suggestion
{% include info title="Note" content="Internally the filenames are put in a list and sorted." %}
```

2021-02-19 01:26 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/83b8ea4bc38cf568328dd24c5edadfbdc108d1df/index.html)

2021-02-19 18:41 UTC, thebeeland requested changes
Most of what I have called out here is cleanup and not really anything that was done incorrectly. Thanks for making so much progress that quickly! I think we'll be at least VERY close to being done with it once you're able to address all of the comments here.

2021-02-19 18:41 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-plugins.md
> +
As mentioned in the example-plugins doc, this content needs to be in example-plugins, and the content currently there needs to be in this document.

2021-02-19 18:41 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-technical-details.md
> +    Toolkit_Folders_Delete
Nothing to change here, I just wanted to note that leaving them like this instead of using the product include is the right decision for now.

2021-02-19 18:41 UTC, thebeeland commented on docs/en/event-daemon/event-daemon.md
> +[![Linting](https://img.shields.io/badge/PEP8%20by-Hound%20CI-a873d1.svg)](https://houndci.com)
Remove all of these. They're relevant for the github repo, so we'll end up keeping them there, but it's not needed in these docs.

2021-02-19 18:41 UTC, thebeeland commented on docs/en/event-daemon/event-daemon.md
> +See the [GitHub Wiki](https://github.com/shotgunsoftware/shotgunEvents/wiki).
Remove this...we don't need it since they're already in the docs.

2021-02-23 19:39 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-configuration.md
> +{% include info title="Note" content="If for some reason the above won't work for you, the search paths for the config file are located in the `_getConfigPath()` function at the bottom of the `{% inc
```suggestion
{% include info title="Note" content="If for some reason the above won't work for you, the search paths for the config file are located in the `_getConfigPath()` function at the bottom of the `shotgunEventDaemon.py` script" %}
```
```suggestion
{% include info title="Note" content="If for some reason the above won't work for you, the search paths for the config file are located in the `_getConfigPath()` function at the bottom of the `{% include product %}EventDaemon.py` script" %}
```

2021-02-23 20:00 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/303e82980d3fd4b7552ebad313bee3fcb68bc725/index.html)

2021-02-23 20:13 UTC, thebeeland commented on docs/en/event-daemon/event-daemon-example-plugins.md
> +There is a [folder of example plugins](https://github.com/shotgunsoftware/shotgunEvents/tree/master/src/examplePlugins) in the source code.
```suggestion
# Example Plugins

There is a [folder of example plugins](https://github.com/shotgunsoftware/shotgunEvents/tree/master/src/examplePlugins) in the source code. 
```

2021-02-23 20:30 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/1dc41f29bd2b1b184777cfca66714cecd8983100/index.html)

2021-02-25 18:41 UTC, thebeeland approved these changes

2021-02-25 18:41 UTC, merged