SG-21570 beyond you first project
shotgunsoftware/developer.shotgunsoftware.com pull request #191
Opened 2021-03-12 17:13 UTC by zamu5

2021-03-12 17:53 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/32755eb4338c4995ef187c164770bd25708155cb/index.html)

2021-03-16 00:22 UTC, thebeeland requested changes
Couple things to sort out, but in general I think it looks pretty good. I'll give it a thorough read once you've made the requested changes just to check on whether any content needs to be updated, as some of this document has been around a long time and might benefit from new info. I'll handle that last part, though, once you polish up those last couple things I mentioned below.

2021-03-16 00:22 UTC, thebeeland commented on docs/en/guides/pipeline-integrations/administration/beyond-your-first-project.md
> +  * [Our Support Team](#our-support-team)
Let's remove the table of contents entirely. What you have here actually looks pretty good, but I don't think the document is long enough to really need one explicitly built into the document like this.

2021-03-16 00:22 UTC, thebeeland commented on docs/en/guides/pipeline-integrations/administration/beyond-your-first-project.md
> +![](https://sg-toolkit.s3.amazonaws.com/tank/docs/docs/55/no_version_0513_171143/beyond_your_first_project/project_ready.png)
Already mentioned this to you elsewhere, but let's get the images into the repo and reference them directly. I'd prefer we stay away from external links like this where possible.

2021-03-16 17:14 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/13ef8b73e06ac67d37f489174d506648c16cc5b9/index.html)

2021-03-16 23:24 UTC, thebeeland requested changes
A little cleanup of some images I don't think we need that were used as thumbnails for links in the document. I'm just removing them and will handle committing that now.

2021-03-16 23:24 UTC, thebeeland commented on docs/en/guides/pipeline-integrations/administration/beyond-your-first-project.md
> +[![](https://sg-toolkit.s3.amazonaws.com/tank/docs/apps/tk-multi-launchapp/v0.10.2_1029_133142/icon_256.png)](https://support.shotgunsoftware.com/hc/en-us/articles/219032968#Use%20Command%20Line%20Ar
```suggestion
- [The Toolkit Application Launcher](https://support.shotgunsoftware.com/hc/en-us/articles/219032968)  
- [Passing Commandline Arguments](https://support.shotgunsoftware.com/hc/en-us/articles/219032968#Use%20Command%20Line%20Arguments%20at%20Launch)    
```

2021-03-16 23:24 UTC, thebeeland commented on docs/en/guides/pipeline-integrations/administration/beyond-your-first-project.md
> +[![](https://sg-toolkit.s3.amazonaws.com/tank/docs/docs/17/no_version_0530_193825/icon_256.png)](https://support.shotgunsoftware.com/hc/en-us/articles/219040678) [> {% include product %} Pipeline Too
```suggestion
[{% include product %} Toolkit Video Collection](https://support.shotgunsoftware.com/hc/en-us/articles/219040678)  
```

2021-03-16 23:24 UTC, thebeeland commented on docs/en/guides/pipeline-integrations/administration/beyond-your-first-project.md
> +[![](https://sg-toolkit.s3.amazonaws.com/tank/docs/docs/11/no_version_0530_204710/icon_256.png)](https://support.shotgunsoftware.com/hc/en-us/articles/219033178) [> How to administer Toolkit.](https:
```suggestion
[How to Administer Toolkit](https://support.shotgunsoftware.com/hc/en-us/articles/219033178)  
```

2021-03-16 23:24 UTC, thebeeland commented on docs/en/guides/pipeline-integrations/administration/beyond-your-first-project.md
> +[![](https://sg-toolkit.s3.amazonaws.com/tank/docs/docs/11/no_version_0530_204710/icon_256.png)](https://support.shotgunsoftware.com/hc/en-us/articles/219033178#Configuring%20Templates) [> File syste
```suggestion
Together, these two parts of the project configuration makes it possible to adjust the various Apps that toolkit use to write out data to locations on disk which make sense are are understood by your existing pipeline.

Read more about this in our advanced documentation:  

- [Folder Configuration](https://support.shotgunsoftware.com/hc/en-us/articles/219033178#Creating%20folders%20on%20disk%20with%20Sgtk)  
- [Filesystem Templates](https://support.shotgunsoftware.com/hc/en-us/articles/219033178#Configuring%20Templates)  
```

2021-03-16 23:24 UTC, thebeeland commented on docs/en/guides/pipeline-integrations/administration/beyond-your-first-project.md
> +[![](https://sg-toolkit.s3.amazonaws.com/tank/zendesk_appstore/tank_logo_256.png)](https://support.shotgunsoftware.com/hc/en-us/articles/219039798) [> The official Toolkit App and Engine listing.](ht
```suggestion
```

2021-03-16 23:24 UTC, thebeeland commented on docs/en/guides/pipeline-integrations/administration/beyond-your-first-project.md
> +[![](https://sg-toolkit.s3.amazonaws.com/tank/docs/docs/10/no_version_0330_043251/icon_256.png)](https://support.shotgunsoftware.com/hc/en-us/articles/219040648) [> An introduction to the high level
```suggestion
[An introduction to the high level concepts in the {% include product %} Toolkit](https://support.shotgunsoftware.com/hc/en-us/articles/219040648)  
```

2021-03-16 23:24 UTC, thebeeland commented on docs/en/guides/pipeline-integrations/administration/beyond-your-first-project.md
> +_Please note that this document describes functionality only available if you have taken control over a Toolkit configuration. For details, see the  [{% include product %} Integrations User Guide](ht
```suggestion
```

2021-03-16 23:43 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/762d458759495c7f140581de3ad8009dd818ba51/index.html)

2021-03-16 23:51 UTC, thebeeland approved these changes
Looks good! I'm going to commit the last couple things at the end of the doc and then will merge. These last two suggestions are just one modernization and removing a bit about our support email address at the end.

2021-03-16 23:51 UTC, thebeeland commented on docs/en/guides/pipeline-integrations/administration/beyond-your-first-project.md
> +## The pipeline Toolkit Community
```suggestion
## The Toolkit Community  
```

2021-03-16 23:51 UTC, thebeeland commented on docs/en/guides/pipeline-integrations/administration/beyond-your-first-project.md
> +Lastly, if you have any questions, ideas or concerns, never hesitate to contact us directly! We try be be practical and hands on with support and if you for example have found a bug, we can often pus
```suggestion
```

2021-03-17 00:20 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/e6540badc3cdf4561f779919d58f2a071d124370/index.html)

2021-03-18 23:59 UTC, merged