SG-25669 Client wants to Modify Schema to Include a Custom Entity for Grouping Tasks Below a Step
shotgunsoftware/developer.shotgunsoftware.com pull request #306
Opened 2022-04-18 15:17 UTC by NorberMV

This pr removes the documentation about creating a custom Pipeline step using a custom entity.

2022-04-18 15:35 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/aa873399150bf18160b03f3862e0de10c863c3ba/index.html)

2022-04-19 14:27 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/bd56ef956d86f015ffb2b46ca0b0229b53547c8f/index.html)

2022-04-19 14:37 UTC, mathurf requested changes

2022-04-19 14:37 UTC, mathurf commented on docs/en/guides/pipeline-integrations/administration/file-system-config-reference.md
> +## How can I create a custom Pipeline Step ?
Need to remove extra white space between `Step  ?`
Otherwise the above link will not work

2022-04-19 17:04 UTC, mathurf approved these changes
LGTM

2022-04-19 19:16 UTC, merged