SG-26445_sg Custom Action Menu Items
shotgunsoftware/developer.shotgunsoftware.com pull request #325
Opened 2022-05-11 12:14 UTC by francoperroneautodesk

2022-05-11 12:33 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/4765de5ae214df84f673dcb8c50c22b713c3f803/index.html)

2022-05-11 14:01 UTC, mathurf commented
This image will also need to be updated. Value should be 2 now
![image](https://user-images.githubusercontent.com/8168836/167868401-783f0a43-647a-4e2b-880a-469557e21b3c.png)

2022-06-03 14:59 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/cfa75d44f85e581df24557db8c3d63ac6fb3d910/index.html)

2022-06-03 18:30 UTC, francoperroneautodesk commented
> @000paradox000 can you help Franco with this documentation page changes. Also look at the Jira ticket, we might want to add something about the fact that Python 2.7 will be deprecated on Nov 1st 2022 and adding a link to Warren's release notes about it.
> 
> Thanks!

Ariell will solve this in a new ticket

2022-06-06 14:34 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/dc6b19133ebef2cbc3189273bb880aa92645eff8/index.html)

2022-06-07 09:49 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/c5c7f167d9fcff28d33f17eee0f9da751276863c/index.html)

2022-06-07 11:00 UTC, toolkitty commented
[Documentation Preview](http://sg-devdocs.s3-website-us-east-1.amazonaws.com/tk-doc-generator/d898f64bb22d8530f9b20bd79cb16d5b09dcb690/index.html)

2022-06-07 14:06 UTC, mathurf requested changes

2022-06-07 14:06 UTC, mathurf commented on docs/en/guides/pipeline-integrations/administration/setting-python-3-desktop.md
Line 36 value should be 2
- For the **Variable name**, add `SHOTGUN_PYTHON_VERSION`, and set the **Variable value** to `3`.

2022-06-07 14:06 UTC, mathurf commented on docs/en/guides/pipeline-integrations/administration/setting-python-3-desktop.md
Line 40 it should mention Python 2
- Restart the {% include product %} Desktop application. Now, you should see that the Python version has been updated to run Python 3.

2022-06-07 14:19 UTC, mathurf approved these changes
LGTM!

2022-06-13 17:56 UTC, merged